# Generated by Django 2.0.6 on 2020-09-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=20, null=True)),
                ('public_time', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
                ('vision', models.IntegerField(blank=True, null=True)),
                ('page_num', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('paper', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('whether', models.IntegerField(blank=True, null=True)),
                ('packing', models.CharField(blank=True, max_length=10, null=True)),
                ('editor_recommend', models.TextField(blank=True, null=True)),
                ('content_recommend', models.TextField(blank=True, null=True)),
                ('about_author', models.TextField(blank=True, null=True)),
                ('catalog', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sale', models.IntegerField(blank=True, null=True)),
                ('new_time', models.DateField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.AddField(
            model_name='tbook',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.TCategory'),
        ),
    ]
