# Generated by Django 2.0.6 on 2020-09-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
